### ISSUE TITLE
Buildfile doesn't work  - build.xml 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dmaidaniuk/content-management-faces#2]
What steps will reproduce the problem?
1. try to run ant build in eclipse or on command line

What is the expected output? What do you see instead?
expected output should be: BUILD SUCCESSFUL 
instead i see: dozens of exceptions due to missing dependencies

What version of the product are you using? On what operating system?
checked out sources from /trunk

Please provide any additional information below.

Original issue reported on code.google.com by `anne.mil...@profitbricks.com` on 3 Nov 2011 at 1:07

**Comment by dmaidaniuk** [comment]
Project will be moved to Maven soon. Thus close this issue as outdated.
